CREATE SEQUENCE SEQ_GUEST;

CREATE TABLE TBL_GUEST(
   ID NUMBER CONSTRAINT PK_GUEST PRIMARY KEY,
   GUEST_NAME VARCHAR2(1000) NOT NULL,
   GUEST_BIRTH DATE
);

SELECT * FROM TBL_GUEST;

INSERT INTO TBL_GUEST
(ID, GUEST_NAME, GUEST_BIRTH)
VALUES(SEQ_MEMBER.NEXTVAL, '정진욱', '1994-12-21');

DROP TABLE TBL_GUEST;


CREATE SEQUENCE SEQ_USER;

CREATE TABLE TBL_USER (
   ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
   USER_NAME VARCHAR2(255) NOT NULL,
   USER_EMAIL VARCHAR2(255) NOT NULL,
   USER_NICKNAME VARCHAR2(255) NOT NULL,
   USER_PHONE VARCHAR2(255) NOT NULL,
   USER_SPORT_KIND VARCHAR2(255),
   USER_BIRTH DATE NOT NULL
);

SELECT * FROM TBL_USER;

INSERT INTO TBL_USER
VALUES(SEQ_MEMBER.NEXTVAL, '정지수', '000jisoo@naver,com', '별쌤', '01052537140', '축구', '1996-07-21');

DROP TABLE TBL_USER;


CREATE SEQUENCE SEQ_MATCHING;

CREATE TABLE TBL_MATCHING(
   ID NUMBER CONSTRAINT PK_MATCHING PRIMARY KEY,
   MATCHING_STATUS VARCHAR2(255) NOT NULL
 );

SELECT * FROM TBL_MATCHING;

INSERT INTO TBL_MATCHING
VALUES(SEQ_MEMBER.NEXTVAL, 'on');

DROP TABLE TBL_MATCHING;


CREATE SEQUENCE SEQ_PLACE;

CREATE TABLE TBL_PLACE(
   ID NUMBER CONSTRAINT PK_PLACE PRIMARY KEY,
   PLACE_DISTRICT VARCHAR2(500) NOT NULL,
   PLACE_PRICE NUMBER DEFAULT 0 NOT NULL
);

SELECT * FROM TBL_PLACE;

INSERT INTO TBL_PLACE
VALUES(SEQ_MEMBER.NEXTVAL, '석촌동 250-1', 5000);

DROP TABLE TBL_PLACE;
