CREATE SEQUENCE SEQ_PRODUCT;

CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255),
	PRODUCT_PRICE NUMBER DEFAULT 0,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE
);

ALTER TABLE TBL_PRODUCT RENAME COLUMN CREATE_DATE TO CREATED_DATE;

SELECT * FROM TBL_PRODUCT;
